### ISSUE TITLE
函数拼写错误

### ISSUE THREAD

**Issue by skyjay8** [somewheve/ctpbee#16]
Func.py里面取消订单拼写有误，cancle正确应该为cancel.

@classmethod
    def generate_cancle_req_by_str(cls, symbol: str, exchange: str, order_id: str):
        if "." in symbol:
            symbol = symbol.split(".")[1]
        return CancelRequest(symbol=symbol, exchange=cls.exchange_map.get(exchange), order_id=order_id)

    @classmethod
    def generate_cancle_req_by_var(cls, symbol: str, exchange: Exchange, order_id: str):
        if "." in symbol:
            symbol = symbol.split(".")[1]
        return CancelRequest(symbol=symbol, exchange=exchange, order_id=order_id)

**Comment by skyjay8** [comment]
@check(type="trader")
    def cancle_order(self, cancle_req: CancelRequest):
        """撤单"""
        cancle_monitor.send(cancle_req)
        self.trader.cancel_order(cancle_req)
这里也是

**Comment by skyjay8** [comment]
__version__ = '0.25'
__status__ = 'dev'
from ctpbee.app import CtpBee
from ctpbee.context import current_app, switch_app, get_app
from ctpbee.func import cancle_order, send_order, CtpbeeApi, subscribe, query_func, auth_time, helper, AsyncApi
from ctpbee.json import dumps, loads
from ctpbee.signals import send_monitor, cancle_monitor

还有这里

**Comment by somewheve** [comment]
已经修复
