### ISSUE TITLE
可以考虑支持FastApi,以替换Flask?

### ISSUE THREAD

**Issue by zfsamzfsam** [somewheve/ctpbee#7]
FastApi好像比Flask更简单更快
https://github.com/tiangolo/fastapi

**Comment by somewheve** [comment]
你的意思是后台 换用fastApi吗  底层支持是采用flask的 , 但是如果支持fastApi  也不难 , 等我把前端代码写完就ok了  ,. 我到时候做个支持 ..这个不难
